### ISSUE TITLE
No sources for video streaming

### ISSUE THREAD

**Issue by MiniChiken** [ReallyFuzzy/LetMeWatchThis.bundle#5]
I'm running into an issue where if I view the LetMeWatchThis channel on my PC I am able to see different streaming sources, but when I choose one of them to stream from the plugin errors out. I also am unable to choose any stream sources on my PS3 when connected to my PLEX Media server. Is this related to one of your previous posts pertaining to alternate streaming servers? If so, would forwarding a specific port solve this issue? I'm using port 32400 for my Server.

**Comment by ReallyFuzzy** [comment]
Most sources should now work.
